image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn -B clean package --file pom.xml
  stage: build
  script:
    - echo "some output here"

test:
  stage: test
  script:
    - mvn -B verify --file pom.xml
